name: Connect to AWS
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install aws cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: amd64
      - name: Get VPC details
        run: aws ec2 describe-vpcs
